export type ComponentName =
    | "attribution"
    | "bearing"
    | "cache"
    | "cover"
    | "direction"
    | "image"
    | "keyboard"
    | "marker"
    | "pointer"
    | "popup"
    | "sequence"
    | "slider"
    | "spatial"
    | "tag"
    | "zoom";
